#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from io import StringIO
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np
import requests
import trimesh
import urllib.request


# ---------------------------------------------------------------------
# Default settings
# ---------------------------------------------------------------------
# No local random seed is used. Coordinates are generated by the HRA 3D Cell Generation API.
DEFAULT_RANDOM_SEED = 42
DEFAULT_NUM_NODES = 1000

# Target anatomical structure inside the local GLB scene.
# For the uploaded female heart model, the matching node is:
# VH_F_right_ventricle
DEFAULT_TARGET_STRUCTURE = "right_ventricle"

# HRA 3D Cell Generation API scene node / file_subpath.
DEFAULT_HRA_SCENE_NODE = "VH_F_right_ventricle"

# HRA reference organ GLB URL sent to the 3D Cell Generation API.
# This should correspond to the same reference organ as the local input GLB.
DEFAULT_HRA_REFERENCE_ORGAN_GLB_URL = (
    "https://cdn.humanatlas.io/digital-objects/ref-organ/heart-female/v1.3/"
    "assets/3d-vh-f-heart.glb"
)

DEFAULT_HRA_3D_CELL_API_URL = (
    "https://apps.humanatlas.io/api/v1/mesh-3d-cell-population"
)

# HRApop filtering defaults.
# This script is intentionally configured for the female right ventricle heart GLB.
DEFAULT_HRA_POP_API_URL = (
    "https://apps.humanatlas.io/api/grlc/hra-pop/"
    "cell_types_in_anatomical_structurescts_per_as"
)

DEFAULT_HRA_ORGAN_FILTER = "heart"
DEFAULT_HRA_AS_FILTER = "right ventricle"
DEFAULT_HRA_TOOL_FILTER = "Azimuth"
DEFAULT_HRA_SEX_FILTER = "Female"

# Built-in default file paths.
DEFAULT_INPUT_GLB = Path("10_organs/downloaded_organs/3d-vh-f-heart.glb")

DEFAULT_OUTPUT_GLB = Path(
    "10_organs/amended_organs/3d-vh-f-heart-right-ventricle-hra-pop-cubes.glb"
)

DEFAULT_CSV_OUTPUT = Path(
    "10_organs/amended_organs/3d-vh-f-heart-right-ventricle-hra-pop-cubes.csv"
)

DEFAULT_HRA_POP_RAW_CSV_OUTPUT = Path(
    "10_organs/amended_organs/hra_pop_raw_cell_types_in_as.csv"
)

DEFAULT_API_GENERATED_CELL_CSV_OUTPUT = Path(
    "10_organs/amended_organs/3d-vh-f-heart-right-ventricle-api-generated-cells.csv"
)

# If None, cube size is calculated from the target structure bounds.
DEFAULT_CUBE_SIZE = None

# Used only when cube size is not manually supplied.
# The cube size becomes this fraction of the target structure's smallest dimension.
DEFAULT_AUTO_CUBE_SIZE_FRACTION = 0.015

NODE_PARENT_NAME = "hra_pop_cell_cube_node"


# ---------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Render HRA 3D Cell Generation API coordinates for right-ventricle "
            "cells using an HRApop/Azimuth-derived cell-type distribution."
        )
    )

    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT_GLB,
        help=f"Path to the input organ GLB. Default: {DEFAULT_INPUT_GLB}",
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_GLB,
        help=f"Path to the output amended GLB. Default: {DEFAULT_OUTPUT_GLB}",
    )

    parser.add_argument(
        "--csv-output",
        type=Path,
        default=DEFAULT_CSV_OUTPUT,
        help=(
            "CSV output path for generated cube positions and selected HRApop "
            f"cell types. Default: {DEFAULT_CSV_OUTPUT}"
        ),
    )

    parser.add_argument(
        "--target-structure",
        type=str,
        default=DEFAULT_TARGET_STRUCTURE,
        help=(
            "Structure name to target inside the local GLB. "
            "Partial matches are allowed. "
            f"Default: {DEFAULT_TARGET_STRUCTURE}."
        ),
    )

    parser.add_argument(
        "--num-nodes",
        type=int,
        default=DEFAULT_NUM_NODES,
        help=f"Number of cell cube nodes to request from the API. Default: {DEFAULT_NUM_NODES}.",
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_RANDOM_SEED,
        help=(
            "Random seed kept for compatibility. The 3D Cell Generation API may not "
            f"use this local seed. Default: {DEFAULT_RANDOM_SEED}."
        ),
    )

    parser.add_argument(
        "--cube-size",
        type=float,
        default=DEFAULT_CUBE_SIZE,
        help=(
            "Manual cube size for generated node cubes. "
            "If omitted, cube size is auto-sized from the target structure bounds."
        ),
    )

    parser.add_argument(
        "--auto-cube-size-fraction",
        type=float,
        default=DEFAULT_AUTO_CUBE_SIZE_FRACTION,
        help=(
            "Fraction of the target structure's smallest dimension used as cube size "
            f"when --cube-size is omitted. Default: {DEFAULT_AUTO_CUBE_SIZE_FRACTION}."
        ),
    )

    parser.add_argument(
        "--hra-pop-csv",
        type=Path,
        default=None,
        help=(
            "Optional local CSV file already exported from the HRApop "
            "cell_types_in_anatomical_structurescts_per_as endpoint. "
            "If omitted, the script attempts to fetch HRApop data from the API."
        ),
    )

    parser.add_argument(
        "--hra-pop-api-url",
        type=str,
        default=DEFAULT_HRA_POP_API_URL,
        help=f"HRApop API URL. Default: {DEFAULT_HRA_POP_API_URL}",
    )

    parser.add_argument(
        "--download-hra-pop-csv",
        type=Path,
        default=DEFAULT_HRA_POP_RAW_CSV_OUTPUT,
        help=(
            "Path where the raw downloaded HRApop table should be saved. "
            f"Default: {DEFAULT_HRA_POP_RAW_CSV_OUTPUT}"
        ),
    )

    parser.add_argument(
        "--hra-organ-filter",
        type=str,
        default=DEFAULT_HRA_ORGAN_FILTER,
        help=f"HRApop organ label filter. Default: {DEFAULT_HRA_ORGAN_FILTER}.",
    )

    parser.add_argument(
        "--hra-as-filter",
        type=str,
        default=DEFAULT_HRA_AS_FILTER,
        help=f"HRApop anatomical structure label filter. Default: {DEFAULT_HRA_AS_FILTER}.",
    )

    parser.add_argument(
        "--hra-tool-filter",
        type=str,
        default=DEFAULT_HRA_TOOL_FILTER,
        help=f"HRApop cell annotation tool filter. Default: {DEFAULT_HRA_TOOL_FILTER}.",
    )

    parser.add_argument(
        "--hra-sex-filter",
        type=str,
        default=DEFAULT_HRA_SEX_FILTER,
        help=(
            "HRApop sex filter. Use an empty string to disable this filter. "
            f"Default: {DEFAULT_HRA_SEX_FILTER}."
        ),
    )

    parser.add_argument(
        "--hra-modality-filter",
        type=str,
        default="",
        help=(
            "Optional HRApop modality filter. Leave empty to accept any modality. "
            "Example: rna."
        ),
    )

    parser.add_argument(
        "--max-cell-types",
        type=int,
        default=0,
        help=(
            "Optional maximum number of highest-count cell types to use. "
            "Use 0 to keep all matching HRApop cell types. Default: 0."
        ),
    )

    parser.add_argument(
        "--hra-reference-organ-glb-url",
        type=str,
        default=DEFAULT_HRA_REFERENCE_ORGAN_GLB_URL,
        help=(
            "Reference organ GLB URL sent to the HRA 3D Cell Generation API. "
            f"Default: {DEFAULT_HRA_REFERENCE_ORGAN_GLB_URL}"
        ),
    )

    parser.add_argument(
        "--hra-scene-node",
        type=str,
        default=DEFAULT_HRA_SCENE_NODE,
        help=(
            "Scene node / file_subpath sent to the HRA 3D Cell Generation API. "
            f"Default: {DEFAULT_HRA_SCENE_NODE}"
        ),
    )

    parser.add_argument(
        "--hra-3d-cell-api-url",
        type=str,
        default=DEFAULT_HRA_3D_CELL_API_URL,
        help=(
            "HRA 3D Cell Generation API URL. "
            f"Default: {DEFAULT_HRA_3D_CELL_API_URL}"
        ),
    )

    parser.add_argument(
        "--api-generated-cell-csv-output",
        type=Path,
        default=DEFAULT_API_GENERATED_CELL_CSV_OUTPUT,
        help=(
            "CSV output path for the raw HRA 3D Cell Generation API response. "
            f"Default: {DEFAULT_API_GENERATED_CELL_CSV_OUTPUT}"
        ),
    )

    return parser.parse_args()


# ---------------------------------------------------------------------
# GLB loading and target mesh selection
# ---------------------------------------------------------------------

def load_glb_as_scene(glb_path: Path) -> trimesh.Scene:
    loaded = trimesh.load(glb_path, force="scene")

    if isinstance(loaded, trimesh.Scene):
        return loaded

    if isinstance(loaded, trimesh.Trimesh):
        scene = trimesh.Scene()
        scene.add_geometry(loaded, node_name="reference_model")
        return scene

    raise TypeError(f"Unsupported GLB type: {type(loaded)}")


def print_available_mesh_nodes(scene: trimesh.Scene) -> None:
    print("Available mesh nodes:")

    for node_name in sorted(scene.graph.nodes_geometry):
        transform, geometry_name = scene.graph[node_name]
        geometry = scene.geometry[geometry_name]

        vertex_count = len(geometry.vertices) if hasattr(geometry, "vertices") else 0
        face_count = len(geometry.faces) if hasattr(geometry, "faces") else 0

        print(
            f"  node={node_name}, geometry={geometry_name}, "
            f"vertices={vertex_count}, faces={face_count}"
        )


def normalize_match_text(value: str) -> str:
    return (
        str(value)
        .lower()
        .replace(" ", "_")
        .replace("-", "_")
        .replace("__", "_")
        .strip()
    )


def find_target_mesh_node(
    scene: trimesh.Scene,
    target_structure: str,
) -> Tuple[str, str, np.ndarray, trimesh.Trimesh]:
    target_normalized = normalize_match_text(target_structure)

    matches: List[Tuple[str, str, np.ndarray, trimesh.Trimesh]] = []

    for node_name in scene.graph.nodes_geometry:
        transform, geometry_name = scene.graph[node_name]
        geometry = scene.geometry[geometry_name]

        if not isinstance(geometry, trimesh.Trimesh):
            continue

        searchable = normalize_match_text(f"{node_name} {geometry_name}")

        if target_normalized in searchable:
            target_mesh = geometry.copy()
            target_mesh.apply_transform(transform)
            matches.append((node_name, geometry_name, transform, target_mesh))

    if not matches:
        print_available_mesh_nodes(scene)

        raise ValueError(
            f"Could not find a mesh node matching target structure: "
            f"{target_structure!r}"
        )

    if len(matches) > 1:
        print("Multiple matching structures were found. Using the first match:")

        for node_name, geometry_name, _, mesh in matches:
            print(
                f"  node={node_name}, geometry={geometry_name}, "
                f"vertices={len(mesh.vertices)}, faces={len(mesh.faces)}"
            )

    return matches[0]


# ---------------------------------------------------------------------
# HRApop loading and filtering
# ---------------------------------------------------------------------

def normalize_filter_text(value: object) -> str:
    return (
        str(value or "")
        .strip()
        .lower()
        .replace("_", " ")
        .replace("-", " ")
    )


def values_match_filter(value: object, filter_value: str) -> bool:
    normalized_filter = normalize_filter_text(filter_value)

    if normalized_filter == "":
        return True

    normalized_value = normalize_filter_text(value)
    return normalized_filter in normalized_value


def parse_float(value: object) -> float:
    if value is None:
        return 0.0

    text = str(value).strip()

    if text == "":
        return 0.0

    try:
        return float(text)
    except ValueError:
        return 0.0


def read_hra_pop_csv(csv_path: Path) -> List[Dict[str, str]]:
    with csv_path.open("r", newline="", encoding="utf-8-sig") as file:
        reader = csv.DictReader(file)
        return [dict(row) for row in reader]


def fetch_url_bytes(url: str, accept: str) -> bytes:
    request = urllib.request.Request(
        url=url,
        headers={
            "Accept": accept,
            "User-Agent": "hra-pop-right-ventricle-glb-script/1.0",
        },
        method="GET",
    )

    with urllib.request.urlopen(request, timeout=120) as response:
        return response.read()


def fetch_hra_pop_rows(api_url: str) -> Tuple[List[Dict[str, str]], bytes]:
    """
    Fetches the HRApop cell summary endpoint.

    The GRLC endpoint commonly returns tabular data. This function first asks
    for CSV. If CSV parsing does not produce useful columns, it tries JSON.
    """
    errors: List[str] = []

    csv_url_candidates = [
        api_url,
        api_url + ".csv" if not api_url.endswith(".csv") else api_url,
        api_url + "?_format=csv" if "?" not in api_url else api_url + "&_format=csv",
    ]

    for url in csv_url_candidates:
        try:
            raw = fetch_url_bytes(url, accept="text/csv")
            decoded = raw.decode("utf-8-sig", errors="replace")

            reader = csv.DictReader(decoded.splitlines())
            rows = [dict(row) for row in reader]

            if rows and "cell_label" in rows[0]:
                return rows, raw

        except Exception as exc:
            errors.append(f"CSV attempt failed for {url}: {exc}")

    json_url_candidates = [
        api_url,
        api_url + ".json" if not api_url.endswith(".json") else api_url,
        api_url + "?_format=json" if "?" not in api_url else api_url + "&_format=json",
    ]

    for url in json_url_candidates:
        try:
            raw = fetch_url_bytes(url, accept="application/json")
            data = json.loads(raw.decode("utf-8", errors="replace"))

            if isinstance(data, list):
                rows = [dict(row) for row in data]
                return rows, raw

            if isinstance(data, dict):
                for key in ("results", "data", "rows"):
                    maybe_rows = data.get(key)

                    if isinstance(maybe_rows, list):
                        rows = [dict(row) for row in maybe_rows]
                        return rows, raw

        except Exception as exc:
            errors.append(f"JSON attempt failed for {url}: {exc}")

    joined_errors = "\n".join(errors)

    raise RuntimeError(
        "Could not fetch HRApop rows from the API. "
        "Export the endpoint as CSV and pass it with --hra-pop-csv.\n"
        f"Attempt details:\n{joined_errors}"
    )


def load_hra_pop_rows(
    hra_pop_csv: Optional[Path],
    api_url: str,
    download_hra_pop_csv: Optional[Path],
) -> List[Dict[str, str]]:
    if hra_pop_csv is not None:
        if not hra_pop_csv.exists():
            raise FileNotFoundError(f"Could not find HRApop CSV: {hra_pop_csv}")

        print(f"Loading HRApop CSV: {hra_pop_csv}")
        return read_hra_pop_csv(hra_pop_csv)

    print(f"Fetching HRApop data from: {api_url}")
    rows, raw = fetch_hra_pop_rows(api_url)

    if download_hra_pop_csv is not None:
        download_hra_pop_csv.parent.mkdir(parents=True, exist_ok=True)
        download_hra_pop_csv.write_bytes(raw)
        print(f"Saved downloaded HRApop response to: {download_hra_pop_csv}")

    return rows


def filter_hra_pop_rows(
    rows: Iterable[Dict[str, str]],
    organ_filter: str,
    as_filter: str,
    tool_filter: str,
    sex_filter: str,
    modality_filter: str,
) -> List[Dict[str, str]]:
    filtered: List[Dict[str, str]] = []

    for row in rows:
        if not values_match_filter(row.get("organ", ""), organ_filter):
            continue

        if not values_match_filter(row.get("as_label", ""), as_filter):
            continue

        if not values_match_filter(row.get("tool", ""), tool_filter):
            continue

        if not values_match_filter(row.get("sex", ""), sex_filter):
            continue

        if not values_match_filter(row.get("modality", ""), modality_filter):
            continue

        filtered.append(row)

    return filtered


def summarize_available_hra_pop_matches(
    rows: Iterable[Dict[str, str]],
    organ_filter: str,
    as_filter: str,
) -> None:
    print("Nearby HRApop rows matching organ/anatomical-structure filters:")

    count = 0

    for row in rows:
        if not values_match_filter(row.get("organ", ""), organ_filter):
            continue

        if not values_match_filter(row.get("as_label", ""), as_filter):
            continue

        print(
            "  "
            f"organ={row.get('organ', '')}, "
            f"as_label={row.get('as_label', '')}, "
            f"sex={row.get('sex', '')}, "
            f"tool={row.get('tool', '')}, "
            f"modality={row.get('modality', '')}, "
            f"cell_label={row.get('cell_label', '')}, "
            f"cell_count={row.get('cell_count', '')}, "
            f"cell_percentage={row.get('cell_percentage', '')}, "
            f"dataset_count={row.get('dataset_count', '')}"
        )

        count += 1

        if count >= 25:
            print("  ...")
            break

    if count == 0:
        print("  No nearby rows found.")


def build_distribution_from_hra_pop_rows(
    rows: List[Dict[str, str]],
    max_cell_types: int,
) -> Dict[str, float]:
    """
    Builds a cell type distribution from HRApop rows.

    Priority:
        1. Use cell_count when available.
        2. Fall back to cell_percentage when count is unavailable.

    Multiple rows with the same cell_label are summed.
    """
    distribution: Dict[str, float] = {}

    for row in rows:
        cell_label = str(row.get("cell_label", "")).strip()

        if cell_label == "":
            continue

        cell_count = parse_float(row.get("cell_count", ""))
        cell_percentage = parse_float(row.get("cell_percentage", ""))

        weight = cell_count if cell_count > 0 else cell_percentage

        if weight <= 0:
            continue

        distribution[cell_label] = distribution.get(cell_label, 0.0) + weight

    if not distribution:
        raise ValueError(
            "No usable HRApop cell distribution could be built from the filtered rows."
        )

    if max_cell_types > 0:
        sorted_items = sorted(
            distribution.items(),
            key=lambda item: item[1],
            reverse=True,
        )

        distribution = dict(sorted_items[:max_cell_types])

    return distribution


def write_hra_pop_distribution_csv(
    csv_output_path: Path,
    distribution: Dict[str, float],
    filtered_rows: List[Dict[str, str]],
) -> None:
    csv_output_path.parent.mkdir(parents=True, exist_ok=True)

    rows_by_label: Dict[str, List[Dict[str, str]]] = {}

    for row in filtered_rows:
        label = str(row.get("cell_label", "")).strip()
        rows_by_label.setdefault(label, []).append(row)

    with csv_output_path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.writer(file)

        writer.writerow(
            [
                "cell_label",
                "distribution_weight",
                "cell_id",
                "organ",
                "organ_id",
                "as",
                "as_label",
                "sex",
                "tool",
                "modality",
                "cell_count",
                "cell_percentage",
                "dataset_count",
            ]
        )

        for cell_label, weight in sorted(
            distribution.items(),
            key=lambda item: item[1],
            reverse=True,
        ):
            matching_rows = rows_by_label.get(cell_label, [])

            if not matching_rows:
                writer.writerow([cell_label, weight])
                continue

            for row in matching_rows:
                writer.writerow(
                    [
                        cell_label,
                        weight,
                        row.get("cell_id", ""),
                        row.get("organ", ""),
                        row.get("organ_id", ""),
                        row.get("as", ""),
                        row.get("as_label", ""),
                        row.get("sex", ""),
                        row.get("tool", ""),
                        row.get("modality", ""),
                        row.get("cell_count", ""),
                        row.get("cell_percentage", ""),
                        row.get("dataset_count", ""),
                    ]
                )


# ---------------------------------------------------------------------
# Distribution utilities
# ---------------------------------------------------------------------

def normalize_distribution(distribution: Dict[str, float]) -> Tuple[List[str], np.ndarray]:
    labels = list(distribution.keys())
    weights = np.array([distribution[label] for label in labels], dtype=float)

    if not labels:
        raise ValueError("Cell type distribution is empty.")

    if np.any(weights < 0):
        raise ValueError("Cell type distribution cannot contain negative values.")

    total = float(np.sum(weights))

    if total <= 0:
        raise ValueError("Cell type distribution must contain at least one positive value.")

    probabilities = weights / total

    return labels, probabilities


def normalize_distribution_to_dict(distribution: Dict[str, float]) -> Dict[str, float]:
    labels, probabilities = normalize_distribution(distribution)

    return {
        label: float(probability)
        for label, probability in zip(labels, probabilities)
    }


def print_distribution_summary(distribution: Dict[str, float]) -> None:
    labels, probabilities = normalize_distribution(distribution)

    rows = sorted(
        zip(labels, probabilities),
        key=lambda item: item[1],
        reverse=True,
    )

    print("HRApop distribution used for 3D Cell Generation API request:")

    for label, probability in rows:
        print(f"  {label}: {probability:.6f}")


# ---------------------------------------------------------------------
# HRA 3D Cell Generation API
# ---------------------------------------------------------------------

def call_3d_cell_api(
    api_url: str,
    file: str,
    scene_node: str,
    num_nodes: int,
    node_distribution: Dict[str, float],
) -> Tuple[np.ndarray, List[str], str]:
    """
    Calls the HRA 3D Cell Generation API.

    The API returns generated x,y,z positions for the selected scene node and
    requested cell type distribution. These are API-generated coordinates, not
    experimentally measured single-cell coordinates.
    """
    payload = {
        "file": file,
        "file_subpath": scene_node,
        "num_nodes": num_nodes,
        "node_distribution": node_distribution,
    }

    response = requests.post(
        api_url,
        json=payload,
        headers={"Content-Type": "application/json"},
        timeout=300,
    )

    response.raise_for_status()

    csv_text = response.text
    reader = csv.DictReader(StringIO(csv_text))
    rows = [dict(row) for row in reader]

    if not rows:
        raise ValueError("3D Cell Generation API returned no rows.")

    actual_columns = set(rows[0].keys())

    possible_cell_type_columns = [
        "Cell Type",
        "cell_type",
        "cell_label",
        "cellLabel",
    ]

    cell_type_column = None

    for candidate in possible_cell_type_columns:
        if candidate in actual_columns:
            cell_type_column = candidate
            break

    required_coordinate_columns = {"x", "y", "z"}

    if not required_coordinate_columns.issubset(actual_columns):
        raise ValueError(
            "3D Cell Generation API response did not contain expected coordinate columns. "
            f"Expected at least: {sorted(required_coordinate_columns)}. "
            f"Actual columns: {sorted(actual_columns)}."
        )

    if cell_type_column is None:
        raise ValueError(
            "3D Cell Generation API response did not contain an expected cell type column. "
            f"Expected one of: {possible_cell_type_columns}. "
            f"Actual columns: {sorted(actual_columns)}."
        )

    points = np.array(
        [
            [
                float(row["x"]),
                float(row["y"]),
                float(row["z"]),
            ]
            for row in rows
        ],
        dtype=float,
    )

    cell_types = [str(row[cell_type_column]) for row in rows]

    return points, cell_types, csv_text


# ---------------------------------------------------------------------
# Cube marker generation
# ---------------------------------------------------------------------

def get_auto_cube_size(
    target_mesh: trimesh.Trimesh,
    auto_cube_size_fraction: float,
) -> float:
    if auto_cube_size_fraction <= 0:
        raise ValueError("Auto cube size fraction must be greater than zero.")

    bounds_min, bounds_max = target_mesh.bounds
    bounds_size = bounds_max - bounds_min

    smallest_dimension = float(np.min(bounds_size))
    cube_size = smallest_dimension * auto_cube_size_fraction

    if cube_size <= 0:
        raise ValueError("Could not compute a valid automatic cube size.")

    return cube_size


def stable_cell_type_seed(cell_type: str) -> int:
    digest = hashlib.sha256(cell_type.encode("utf-8")).digest()
    return int.from_bytes(digest[:4], byteorder="little", signed=False)


def cell_type_to_color(cell_type: str) -> np.ndarray:
    """
    Creates a stable pseudo-random color from the cell type name.
    """
    seed = stable_cell_type_seed(cell_type)
    local_rng = np.random.default_rng(seed)

    rgb = local_rng.integers(low=40, high=256, size=3, dtype=np.uint8)
    rgba = np.array([rgb[0], rgb[1], rgb[2], 255], dtype=np.uint8)

    return rgba


def make_cube_marker(
    center: np.ndarray,
    cube_size: float,
    cell_type: str,
) -> trimesh.Trimesh:
    cube = trimesh.creation.box(
        extents=(cube_size, cube_size, cube_size)
    )

    cube.apply_translation(center)
    cube.visual.face_colors = cell_type_to_color(cell_type)

    return cube


def safe_name(value: str) -> str:
    cleaned = value.strip()
    cleaned = cleaned.replace(" ", "_")
    cleaned = cleaned.replace("/", "_")
    cleaned = cleaned.replace("\\", "_")
    cleaned = cleaned.replace(":", "_")
    cleaned = cleaned.replace(";", "_")
    cleaned = cleaned.replace(",", "_")
    cleaned = cleaned.replace("(", "")
    cleaned = cleaned.replace(")", "")
    cleaned = cleaned.replace("[", "")
    cleaned = cleaned.replace("]", "")
    cleaned = cleaned.replace("{", "")
    cleaned = cleaned.replace("}", "")

    return cleaned


def add_cube_nodes_to_scene(
    scene: trimesh.Scene,
    points: np.ndarray,
    cell_types: List[str],
    cube_size: float,
    target_structure_name: str,
) -> None:
    if len(points) != len(cell_types):
        raise ValueError("Point count and cell type count do not match.")

    target_name = safe_name(target_structure_name)

    for index, (point, cell_type) in enumerate(zip(points, cell_types)):
        cube = make_cube_marker(
            center=point,
            cube_size=cube_size,
            cell_type=cell_type,
        )

        cell_type_name = safe_name(cell_type)

        scene.add_geometry(
            cube,
            node_name=(
                f"{NODE_PARENT_NAME}_{target_name}_"
                f"{index:05d}_{cell_type_name}"
            ),
            geom_name=(
                f"{NODE_PARENT_NAME}_geometry_{target_name}_"
                f"{index:05d}_{cell_type_name}"
            ),
        )


# ---------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------

def export_scene_as_glb(scene: trimesh.Scene, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    exported = scene.export(file_type="glb")

    if isinstance(exported, bytes):
        output_path.write_bytes(exported)
    else:
        output_path.write_bytes(bytes(exported))


def write_nodes_csv(
    csv_output_path: Path,
    points: np.ndarray,
    cell_types: List[str],
    target_node_name: str,
    target_geometry_name: str,
    distribution: Dict[str, float],
    source_api_url: str,
    source_file_url: str,
    source_scene_node: str,
) -> None:
    csv_output_path.parent.mkdir(parents=True, exist_ok=True)

    total_weight = float(sum(distribution.values()))

    with csv_output_path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.writer(file)
        writer.writerow(
            [
                "index",
                "x",
                "y",
                "z",
                "cell_type",
                "cell_type_distribution_weight",
                "cell_type_distribution_probability",
                "target_node_name",
                "target_geometry_name",
                "source_api_url",
                "source_file_url",
                "source_scene_node",
            ]
        )

        for index, (point, cell_type) in enumerate(zip(points, cell_types)):
            weight = float(distribution.get(cell_type, 0.0))
            probability = weight / total_weight if total_weight > 0 else 0.0

            writer.writerow(
                [
                    index,
                    float(point[0]),
                    float(point[1]),
                    float(point[2]),
                    cell_type,
                    weight,
                    probability,
                    target_node_name,
                    target_geometry_name,
                    source_api_url,
                    source_file_url,
                    source_scene_node,
                ]
            )


def print_cell_type_summary(cell_types: List[str]) -> None:
    unique, counts = np.unique(np.array(cell_types), return_counts=True)

    print("Generated cell type counts from 3D Cell Generation API response:")

    for label, count in sorted(zip(unique, counts), key=lambda item: item[0]):
        print(f"  {label}: {count}")


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def main() -> None:
    args = parse_args()

    input_glb: Path = args.input
    output_glb: Path = args.output

    if not input_glb.exists():
        raise FileNotFoundError(f"Could not find input GLB: {input_glb}")

    if args.num_nodes <= 0:
        raise ValueError("--num-nodes must be greater than zero.")

    if args.max_cell_types < 0:
        raise ValueError("--max-cell-types must be greater than or equal to zero.")

    print(f"Loading local GLB: {input_glb}")

    scene = load_glb_as_scene(input_glb)

    (
        target_node_name,
        target_geometry_name,
        target_transform,
        target_mesh,
    ) = find_target_mesh_node(
        scene=scene,
        target_structure=args.target_structure,
    )

    bounds_min, bounds_max = target_mesh.bounds
    bounds_size = bounds_max - bounds_min

    cube_size = (
        args.cube_size
        if args.cube_size is not None
        else get_auto_cube_size(
            target_mesh=target_mesh,
            auto_cube_size_fraction=args.auto_cube_size_fraction,
        )
    )

    if cube_size <= 0:
        raise ValueError("Cube size must be greater than zero.")

    print("Loading HRApop cell type distribution.")

    hra_rows = load_hra_pop_rows(
        hra_pop_csv=args.hra_pop_csv,
        api_url=args.hra_pop_api_url,
        download_hra_pop_csv=args.download_hra_pop_csv,
    )

    filtered_hra_rows = filter_hra_pop_rows(
        rows=hra_rows,
        organ_filter=args.hra_organ_filter,
        as_filter=args.hra_as_filter,
        tool_filter=args.hra_tool_filter,
        sex_filter=args.hra_sex_filter,
        modality_filter=args.hra_modality_filter,
    )

    if not filtered_hra_rows:
        summarize_available_hra_pop_matches(
            rows=hra_rows,
            organ_filter=args.hra_organ_filter,
            as_filter=args.hra_as_filter,
        )

        raise ValueError(
            "No HRApop rows matched the selected filters. "
            "Try relaxing --hra-sex-filter, --hra-modality-filter, "
            "or inspect the downloaded/raw HRApop CSV."
        )

    distribution = build_distribution_from_hra_pop_rows(
        rows=filtered_hra_rows,
        max_cell_types=args.max_cell_types,
    )

    node_distribution = normalize_distribution_to_dict(distribution)

    print(f"Target structure search: {args.target_structure}")
    print(f"Matched local target node: {target_node_name}")
    print(f"Matched local target geometry: {target_geometry_name}")
    print(f"Target vertices: {len(target_mesh.vertices)}")
    print(f"Target faces: {len(target_mesh.faces)}")
    print(f"Target watertight: {target_mesh.is_watertight}")
    print(f"Target bounds min: {bounds_min}")
    print(f"Target bounds max: {bounds_max}")
    print(f"Target bounds size: {bounds_size}")
    print(f"Requested node count: {args.num_nodes}")
    print(f"Cube size: {cube_size}")
    print(f"HRApop rows loaded: {len(hra_rows)}")
    print(f"HRApop rows after filters: {len(filtered_hra_rows)}")
    print(f"HRApop organ filter: {args.hra_organ_filter}")
    print(f"HRApop AS filter: {args.hra_as_filter}")
    print(f"HRApop tool filter: {args.hra_tool_filter}")
    print(f"HRApop sex filter: {args.hra_sex_filter}")
    print(f"HRApop modality filter: {args.hra_modality_filter}")
    print(f"HRA 3D Cell API URL: {args.hra_3d_cell_api_url}")
    print(f"HRA reference organ GLB URL: {args.hra_reference_organ_glb_url}")
    print(f"HRA scene node: {args.hra_scene_node}")

    print_distribution_summary(distribution)

    print("Calling HRA 3D Cell Generation API for coordinate generation.")

    points, cell_types, api_generated_csv_text = call_3d_cell_api(
        api_url=args.hra_3d_cell_api_url,
        file=args.hra_reference_organ_glb_url,
        scene_node=args.hra_scene_node,
        num_nodes=args.num_nodes,
        node_distribution=node_distribution,
    )

    if len(points) == 0:
        raise ValueError("No points were returned from the HRA 3D Cell Generation API.")

    print(f"3D Cell Generation API returned points: {len(points)}")

    if args.api_generated_cell_csv_output is not None:
        args.api_generated_cell_csv_output.parent.mkdir(parents=True, exist_ok=True)
        args.api_generated_cell_csv_output.write_text(
            api_generated_csv_text,
            encoding="utf-8",
        )

        print(
            "Exported raw 3D Cell Generation API CSV to: "
            f"{args.api_generated_cell_csv_output}"
        )

    print_cell_type_summary(cell_types)

    add_cube_nodes_to_scene(
        scene=scene,
        points=points,
        cell_types=cell_types,
        cube_size=cube_size,
        target_structure_name=target_node_name,
    )

    export_scene_as_glb(scene, output_glb)

    print(f"Exported modified GLB to: {output_glb}")

    if args.csv_output is not None:
        write_nodes_csv(
            csv_output_path=args.csv_output,
            points=points,
            cell_types=cell_types,
            target_node_name=target_node_name,
            target_geometry_name=target_geometry_name,
            distribution=distribution,
            source_api_url=args.hra_3d_cell_api_url,
            source_file_url=args.hra_reference_organ_glb_url,
            source_scene_node=args.hra_scene_node,
        )

        print(f"Exported generated node CSV to: {args.csv_output}")

        distribution_csv = args.csv_output.with_name(
            args.csv_output.stem + "_hra_pop_distribution.csv"
        )

        write_hra_pop_distribution_csv(
            csv_output_path=distribution_csv,
            distribution=distribution,
            filtered_rows=filtered_hra_rows,
        )

        print(f"Exported HRApop distribution CSV to: {distribution_csv}")


if __name__ == "__main__":
    main()