"""
Generate Unity C# Editor Script to create ScriptableObjects from CSVs
"""

import pandas as pd
import yaml
from pathlib import Path
from tqdm import tqdm

def load_config():
    """Load configuration from config.yaml"""
    config_path = Path(__file__).parent / "config.yaml"
    with open(config_path, 'r') as f:
        return yaml.safe_load(f)

def escape_csharp_string(value):
    """Escape special characters for C# strings"""
    if value is None or pd.isna(value):
        return ""
    s = str(value)
    s = s.replace('\\', '\\\\')  # Escape backslashes
    s = s.replace('"', '\\"')    # Escape quotes
    s = s.replace('\n', '\\n')   # Escape newlines
    return s

def generate_as_code(csv_path):
    """Generate C# code for AS ScriptableObjects"""
    df = pd.read_csv(csv_path)
    
    code_lines = []
    code_lines.append("        // Create AS ScriptableObject")
    code_lines.append("        var asData = ScriptableObject.CreateInstance<SOHraApiAsCellSummaries>();")
    code_lines.append("        asData.rows = new List<CellSummaryRow>();")
    code_lines.append("")
    
    for idx, row in tqdm(df.iterrows(), total=len(df), desc="  Generating AS code"):
        code_lines.append("        asData.rows.Add(new CellSummaryRow {")
        code_lines.append(f'            organ = "{escape_csharp_string(row["organ"])}",')
        code_lines.append(f'            asId = "{escape_csharp_string(row["as"])}",')
        code_lines.append(f'            asLabel = "{escape_csharp_string(row["as_label"])}",')
        code_lines.append(f'            sex = "{escape_csharp_string(row["sex"])}",')
        code_lines.append(f'            tool = "{escape_csharp_string(row["tool"])}",')
        code_lines.append(f'            modality = "{escape_csharp_string(row["modality"])}",')
        code_lines.append(f'            cellId = "{escape_csharp_string(row["cell_id"])}",')
        code_lines.append(f'            cellLabel = "{escape_csharp_string(row["cell_label"])}",')
        code_lines.append(f'            cellCount = {float(row["cell_count"])}f,')
        code_lines.append(f'            cellPercentage = {float(row["cell_percentage"])}f,')
        code_lines.append(f'            datasetCount = {int(row["dataset_count"])}')
        code_lines.append("        });")
        code_lines.append("")
    
    code_lines.append('        AssetDatabase.CreateAsset(asData, "Assets/ScriptableObjects/AsCellSummaries.asset");')
    code_lines.append(f'        Debug.Log("Created AS ScriptableObject with {len(df)} rows");')
    
    return "\n".join(code_lines)

def generate_es_code(csv_path):
    """Generate C# code for ES ScriptableObjects"""
    df = pd.read_csv(csv_path)
    
    code_lines = []
    code_lines.append("        // Create ES ScriptableObject")
    code_lines.append("        var esData = ScriptableObject.CreateInstance<SOHraApiEsCellSummaries>();")
    code_lines.append("        esData.rows = new List<ExtractionSiteSummaryRow>();")
    code_lines.append("")
    
    for idx, row in tqdm(df.iterrows(), total=len(df), desc="  Generating ES code"):
        code_lines.append("        esData.rows.Add(new ExtractionSiteSummaryRow {")
        code_lines.append(f'            organId = "{escape_csharp_string(row["organ_id"])}",')
        code_lines.append(f'            organ = "{escape_csharp_string(row["organ"])}",')
        code_lines.append(f'            extractionSite = "{escape_csharp_string(row["extraction_site"])}",')
        code_lines.append(f'            sex = "{escape_csharp_string(row["sex"])}",')
        code_lines.append(f'            tool = "{escape_csharp_string(row["tool"])}",')
        code_lines.append(f'            modality = "{escape_csharp_string(row["modality"])}",')
        code_lines.append(f'            cellId = "{escape_csharp_string(row["cell_id"])}",')
        code_lines.append(f'            cellLabel = "{escape_csharp_string(row["cell_label"])}",')
        code_lines.append(f'            cellCount = {float(row["cell_count"])}f,')
        code_lines.append(f'            cellPercentage = {float(row["cell_percentage"])}f,')
        code_lines.append("        });")
        code_lines.append("")
    
    code_lines.append('        AssetDatabase.CreateAsset(esData, "Assets/ScriptableObjects/EsCellSummaries.asset");')
    code_lines.append(f'        Debug.Log("Created ES ScriptableObject with {len(df)} rows");')
    
    return "\n".join(code_lines)

def generate_unity_script(as_code, es_code, output_path):
    """Generate complete Unity Editor Script"""
    
    script = f'''using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

/// <summary>
/// Auto-generated script to create ScriptableObjects from HRA cell population data
/// Generated by: 01-generate-scriptable-objects.py
/// </summary>
public class CreateCellSummaries : EditorWindow
{{
    [MenuItem("Tools/Generate Cell Summary ScriptableObjects")]
    public static void Generate()
    {{
        Debug.Log("Generating Cell Summary ScriptableObjects...");
        
{as_code}
        
{es_code}
        
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        
        Debug.Log("✓ ScriptableObjects created successfully!");
    }}
}}
'''
    
    with open(output_path, 'w') as f:
        f.write(script)

def main():
    config = load_config()
    
    script_dir = Path(__file__).parent
    input_dir = (script_dir / config['paths']['input_dir']).resolve()
    output_dir = (script_dir / config['paths']['output_dir']).resolve()
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print("=" * 60)
    print("HRA Cell Populations - Generate Unity Script")
    print("=" * 60)
    print()
    
    # Generate AS code
    print("1. Processing Anatomical Structure (AS) data...")
    as_csv = input_dir / "as-ct-hra-pop.csv"
    as_code = generate_as_code(as_csv)
    
    # Generate ES code
    print("2. Processing Extraction Site (ES) data...")
    es_csv = input_dir / "es-ct-hra-pop.csv"
    es_code = generate_es_code(es_csv)
    
    # Generate Unity script
    print("3. Generating Unity C# script...")
    output_script = output_dir / "CreateCellSummaries.cs"
    generate_unity_script(as_code, es_code, output_script)
    
    print("=" * 60)
    print("✓ Unity script generated!")
    print(f"File: {output_script}")
    print("=" * 60)
    print()
    print("Next steps:")
    print("1. Copy CreateCellSummaries.cs to Unity project's Editor folder")
    print("2. In Unity: Tools → Generate Cell Summary ScriptableObjects")

if __name__ == "__main__":
    main()